import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

export const generatePDF = async (text, fileName) => {
  return new Promise((resolve, reject) => {
    let doc;
    let stream;
    let filePath;
    
    try {
      const sanitizedFileName = fileName
        .replace(/[^a-zA-Z0-9-_]/g, "_")
        .replace(/_+/g, "_")
        .substring(0, 50);
      
      const relativePath = `uploads/generated_${sanitizedFileName}_${Date.now()}.pdf`;
      filePath = path.join(process.cwd(), relativePath);
      
      const dir = path.dirname(filePath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      
      doc = new PDFDocument({
        size: "A4",
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        info: {
          Title: `SYNAPSE Report - ${sanitizedFileName}`,
          Author: "SYNAPSE Neural Interface AI",
          Subject: "AI Generated Report",
          CreationDate: new Date()
        }
      });
      
      stream = fs.createWriteStream(filePath);
      
      stream.on("error", (err) => {
        console.error("PDF stream error:", err.message);
        cleanup();
        reject(new Error("Failed to write PDF file"));
      });
      
      doc.on("error", (err) => {
        console.error("PDF document error:", err.message);
        cleanup();
        reject(new Error("PDF generation failed"));
      });
      
      doc.pipe(stream);
      
      const cleanText = text
        .replace(/\*\*/g, "")
        .replace(/\*/g, "")
        .replace(/#{1,6}\s/g, "")
        .replace(/```[\s\S]*?```/g, "[Code Block]")
        .replace(/`([^`]+)`/g, "$1")
        .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
        .substring(0, 50000);
      
      doc.fontSize(20).fillColor("#0891b2").text("SYNAPSE Generated Report", { align: "center" });
      doc.moveDown(0.5);
      
      doc.fontSize(10).fillColor("#64748b").text(`Generated: ${new Date().toLocaleString()}`, { align: "center" });
      doc.moveDown(2);
      
      doc.fontSize(12).fillColor("#1e293b");
      
      const lines = cleanText.split("\n");
      
      for (const line of lines) {
        if (line.trim() === "") {
          doc.moveDown(0.5);
          continue;
        }
        
        if (line.startsWith("#")) {
          const titleText = line.replace(/^#+\s*/, "");
          doc.fontSize(16).fillColor("#0891b2").text(titleText, { align: "left" });
          doc.moveDown(0.5);
          doc.fontSize(12).fillColor("#1e293b");
          continue;
        }
        
        if (line.startsWith("- ") || line.startsWith("* ")) {
          const bulletText = line.substring(2);
          doc.fontSize(11).fillColor("#334155").text(`• ${bulletText}`, { indent: 20 });
          continue;
        }
        
        try {
          doc.fontSize(11).fillColor("#1e293b").text(line, { 
            align: "left", 
            lineGap: 2,
            continued: false
          });
        } catch (textErr) {
          console.warn("Failed to write text line:", textErr.message);
        }
      }
      
      doc.moveDown(3);
      doc.fontSize(8).fillColor("#94a3b8").text("Generated by SYNAPSE Neural Interface AI", { align: "center" });
      
      doc.end();
      
      const finishTimeout = setTimeout(() => {
        if (fs.existsSync(filePath)) {
          resolve(relativePath);
        } else {
          reject(new Error("PDF file was not created within timeout"));
        }
      }, 10000);
      
      stream.on("finish", () => {
        clearTimeout(finishTimeout);
        if (fs.existsSync(filePath)) {
          resolve(relativePath);
        } else {
          reject(new Error("PDF file was not created"));
        }
      });
      
    } catch (err) {
      console.error("PDF generation error:", err.message);
      cleanup();
      reject(err);
    }
    
    function cleanup() {
      try {
        if (stream) stream.destroy();
        if (doc) doc.end();
        if (filePath && fs.existsSync(filePath)) {
          fs.unlinkSync(filePath);
        }
      } catch (cleanupErr) {
        console.warn("PDF cleanup error:", cleanupErr.message);
      }
    }
  });
};
